global.COLOR_RED = "COLOR_RED";
global.COLOR_GREEN = "COLOR_GREEN";
global.COLOR_BLUE = "COLOR_BLUE";

global.COLOR_YELLOW = "COLOR_YELLOW";
global.COLOR_CYAN = "COLOR_CYAN";
global.COLOR_MAGENTA = "COLOR_MAGENTA";

global.COLOR_NONE = "COLOR_NONE";

room_goto_next();